services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - redDocker

  wordpress:
    image: bitnami/wordpress:latest
    ports:
      - "82:8080"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/bitnami/wordpress
    networks:
      - redDocker

volumes:
  mariadb_data:
  wordpress_data:

networks:
  redDocker: